### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by lbineau** [oyvindhermansen/heightify#42]
Hello,

Could you add a destroy methods to stop the module watchers to avoid zombie objects.
I try to use it with Vue.js for example and I want to destroy the behavior when the component is detached from the DOM

Thank you

**Comment by oyvindhermansen** [comment]
Hey @lbineau ! 

Thank you for posting the issue! 

I will look into this, but don't know how fast I will be able to implement it. If you have a solution, you are very welcome to send a PR :)

Just for curiousity, do you find heightify helpfull in general?

**Comment by lbineau** [comment]
No need to hurry because finally my client is using IE10+ so I end up with flexbox it is much more convenient :)
I did not tested the library so far but I wanted to find something like http://brm.io/jquery-match-height-demo/ without jQuery.
After checking the source code it seems that you don't use any observer on resize so no need to have a destroy method on the instance :)
